INSERT INTO `calestore`.`ASPECT` (`ASPECT_ID`,`CATEGORY_ID`,`ASPECT_NAME`) VALUES (0,1,'Operating Sytem');

INSERT INTO `calestore`.`ASPECT` (`ASPECT_ID`,`CATEGORY_ID`,`ASPECT_NAME`) VALUES (0,1,'Processor');

INSERT INTO `calestore`.`ASPECT` (`ASPECT_ID`,`CATEGORY_ID`,`ASPECT_NAME`) VALUES (0,1,'Memory');

INSERT INTO `calestore`.`ASPECT` (`ASPECT_ID`,`CATEGORY_ID`,`ASPECT_NAME`) VALUES (0,1,'Storage');

INSERT INTO `calestore`.`ASPECT` (`ASPECT_ID`,`CATEGORY_ID`,`ASPECT_NAME`) VALUES (0,1,'Warranty');

INSERT INTO `calestore`.`ASPECT` (`ASPECT_ID`,`CATEGORY_ID`,`ASPECT_NAME`) VALUES (0,1,'User Rating');

INSERT INTO `calestore`.`ASPECT` (`ASPECT_ID`,`CATEGORY_ID`,`ASPECT_NAME`) VALUES (0,7,'License');

INSERT INTO `calestore`.`ASPECT` (`ASPECT_ID`,`CATEGORY_ID`,`ASPECT_NAME`) VALUES (0,4,'Measurement');

INSERT INTO `calestore`.`ASPECT` (`ASPECT_ID`,`CATEGORY_ID`,`ASPECT_NAME`) VALUES (0,4,'Weight');

INSERT INTO `calestore`.`ASPECT` (`ASPECT_ID`,`CATEGORY_ID`,`ASPECT_NAME`) VALUES (0,4,'Material');

INSERT INTO `calestore`.`ASPECT` (`ASPECT_ID`,`CATEGORY_ID`,`ASPECT_NAME`) VALUES (0,5,'Extendable Warranty');

INSERT INTO `calestore`.`ASPECT` (`ASPECT_ID`,`CATEGORY_ID`,`ASPECT_NAME`) VALUES (0,5,'Warranty period');

INSERT INTO `calestore`.`ASPECT` (`ASPECT_ID`,`CATEGORY_ID`,`ASPECT_NAME`) VALUES (0,5,'Telephone Support');

INSERT INTO `calestore`.`ASPECT` (`ASPECT_ID`,`CATEGORY_ID`,`ASPECT_NAME`) VALUES (0,5,'Transferable');
