INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'admin','admin','admin@cal-estore.com','YWRtaW4=',
'00000','M','A',null,'A',null,
1,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user1','user1','user1@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
1,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user2','user2','user2@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
1,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user3','user3','user3@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
2,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user4','user4','user4@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
2,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user5','user5','user5@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
3,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user6','user6','user6@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
1,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user7','user7','user7@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
10,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user8','user8','user8@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
10,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user9','user9','user9@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
10,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user10','user10','user10@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
9,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user11','user11','user11@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
9,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user12','user12','user12@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
9,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user13','user13','user13@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
3,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user14','user14','user14@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
3,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user15','user15','user15@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
3,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user16','user16','user16@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
8,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user17','user17','user17@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
8,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user18','user18','user18@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
8,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user19','user19','user19@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
4,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user20','user20','user20@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
4,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user21','user21','user21@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
4,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user22','user22','user22@test.com','MTIzNDU2',
'00000','M','U',null,'A',null,
5,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user23','user23','user23@test.com','MTIzNDU2',
'00000','M','U',null,'I',null,
5,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user24','user24','user24@test.com','MTIzNDU2',
'00000','M','U',null,'I',null,
5,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user25','user25','user25@test.com','MTIzNDU2',
'00000','M','U',null,'I',null,
6,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user26','user26','user26@test.com','MTIzNDU2',
'00000','M','U',null,'I',null,
6,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user27','user27','user27@test.com','MTIzNDU2',
'00000','M','U',null,'I',null,
6,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user28','user28','user28@test.com','MTIzNDU2',
'00000','M','U',null,'I',null,
1,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user29','user29','user29@test.com','MTIzNDU2',
'00000','M','U',null,'I',null,
1,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user30','user30','user30@test.com','MTIzNDU2',
'00000','M','U',null,'I',null,
1,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user31','user31','user31@test.com','MTIzNDU2',
'00000','M','U',null,'I',null,
1,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user32','user32','user32@test.com','MTIzNDU2',
'00000','M','U',null,'I',null,
1,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user33','user33','user33@test.com','MTIzNDU2',
'00000','M','U',null,'I',null,
1,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user34','user34','user34@test.com','MTIzNDU2',
'00000','M','U',null,'I',null,
1,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user35','user35','user35@test.com','MTIzNDU2',
'00000','M','U',null,'I',null,
1,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user36','user36','user36@test.com','MTIzNDU2',
'00000','M','U',null,'I',null,
1,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user37','user37','user37@test.com','MTIzNDU2',
'00000','M','U',null,'I',null,
1,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user38','user38','user38@test.com','MTIzNDU2',
'00000','M','U',null,'I',null,
1,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user39','user39','user39@test.com','MTIzNDU2',
'00000','M','U',null,'I',null,
1,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'user40','user40','user40@test.com','MTIzNDU2',
'00000','M','U',null,'I',null,
1,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'Florinda','Sanchez','florinda@cal.com','ZmxvcmluZGFAMTI=',
'842-357-8075','F','A',null,'A',null,
102,'Y','Y');

INSERT INTO `calestore`.`USER_PROFILE` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`,`EMAIL_ID`,`PASSWORD`,
`MOBILE_NUMBER`,`GENDER`,`PROFILE_IND`,`CREATED_DATE`,`STATUS_IND`,`END_DATE`,
`DEPARTMENT_ID`,`EMAIL_PREF_IND`,`SMS_PREF_IND`) 
VALUES (0,'Emma','Mercier','emma@cal.com','ZW1tYUAxMg==',
'794-058-3514','F','U',null,'A',null,
262,'Y','Y');