INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (1,1,'Windows 10 Pro (64 bit)');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (1,2,'Core i5-6500T, 2.5GHz');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (1,3,'8 GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (1,4,'500GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (1,5,'2 year');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (2,1,'Windows 10 Pro (32/64 bit)');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (2,2,'Core i5-6500T, 2.5GHz');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (2,3,'4 GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (2,4,'400GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (2,5,'2 year');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (3,1,'Windows 7 Pro (32/64 bit)');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (3,2,'Core i5-6500T, 2.5GHz');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (3,3,'4 GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (3,4,'500GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (3,5,'3 year');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (4,1,'Microsoft Windows 7 Professional 64 bit');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (4,2,'Intel Core i5-6500 ');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (4,3,'4 GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (4,4,'500 GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (4,5,'3/3/3 (material/labor/onsite) SFF/ST Warranty US');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (5,1,'Microsoft Windows 7 Professional 64');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (5,2,'Intel Core i5-6500 ');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (5,3,'8 GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (5,4,'500 GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (5,5,'3/3/3 (material/labor/onsite) SFF/ST Warranty US');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (6,1,'Windows 10');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (6,2,'UMA i5-6300U');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (6,3,'4GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (6,4,'500GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (6,5,'3 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (6,6,'5');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (7,1,'Windows 7');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (7,2,'i5-6200U');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (7,3,'4GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (7,4,'400GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (7,5,'1 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (7,6,'3');


INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (8,1,'Windows 10');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (8,2,'UMA i7-6700HQ');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (8,3,'8GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (8,4,'1TB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (8,5,'2 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (8,6,'5');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (9,1,'Windows 10');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (9,2,'i5-6200U');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (9,3,'4GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (9,4,'128GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (9,5,'1 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (9,6,'4');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (10,1,'Windows 10 Pro');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (10,2,'i5-6200U');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (10,3,'4GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (10,4,'500GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (10,5,'2 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (10,6,'3');


INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (11,1,'Windows 10 Pro 64');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (11,2,'Core i7');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (11,3,'16GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (11,4,'256GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (11,5,'3 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (11,6,'4');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (12,1,'Windows 7 Professional 64 650');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (12,2,'UMA i7-6600U');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (12,3,'16 GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (12,4,'1 TB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (12,5,'3 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (12,6,'5');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (13,1,'Windows 7 Professional 64 640');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (13,2,'UMA i7-6600U');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (13,3,'8 GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (13,4,'256 GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (13,5,'3 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (13,6,'5');


INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (14,1,'Microsoft Windows 7 Professional 64 bit');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (14,2,' Intel Core i5-6500');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (14,3,'4GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (14,4,'500GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (14,5,'1 year');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (15,1,'Microsoft Windows 7 Professional 64 bit');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (15,2,'Core i5-6500 3.2GHz');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (15,3,'4GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (15,4,'500GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (15,5,'3 year');


INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (16,12,'2 Years');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (17,11,'Yes');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (17,12,'1 Years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (17,13,'Yes');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (17,14,'No');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (18,11,'Yes');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (18,12,'3 Years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (18,13,'Yes');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (18,14,'No');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (19,11,'No');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (19,12,'2 Years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (19,13,'Yes');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (19,14,'No');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (20,11,'Yes');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (20,12,'2 Years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (20,13,'Yes');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (20,14,'Yes');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (21,11,'NA');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (21,12,'NA');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (21,13,'Yes');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (21,14,'No');


INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (22,11,'NA');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (22,12,'4 Years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (22,13,'Yes');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (22,14,'Yes');


INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (23,11,'No');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (23,12,'3 Years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (23,13,'Yes');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (23,14,'Yes');


INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (24,11,'Yes');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (24,12,'1 Years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (24,13,'Yes');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (24,14,'No');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (25,11,'Yes');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (25,12,'3 Years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (25,13,'Yes');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (25,14,'No');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (26,11,'Yes');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (26,12,'2 Years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (26,13,'Yes');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (26,14,'No');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (27,11,'No');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (27,12,'4 Years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (27,13,'Yes');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (27,14,'No');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (28,11,'NA');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (28,12,'NA');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (28,13,'Yes');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (28,14,'Yes');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (29,11,'Yes');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (29,12,'5 Years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (29,13,'Yes');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (29,14,'No');


INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (30,12,'3 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (31,12,'5 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (32,12,'2 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (33,12,'3 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (34,12,'3 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (35,12,'3 years');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (36,1,'Windows 10 Pro 64-bit (Windows 7 Compatible)');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (36,2,'i5-6200U');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (36,3,'4GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (36,4,'128GB');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (36,5,'2 years');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (37,12,'5 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (38,12,'3 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (39,12,'3 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (40,12,'1 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (41,12,'1 years');

INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (42,12,'1 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (43,12,'4 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (44,12,'5 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (45,12,'2 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (46,12,'1 years');
INSERT INTO `calestore`.`PRODUCT_ASPECT` (`PRODUCT_ID`,`ASPECT_ID`,`ASPECT_VAL`) VALUES (47,12,'2 years');


