package com.hpe.calEStore.dao.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrderStatusId generated by hbm2java
 */
@Embeddable
public class OrderStatusId implements java.io.Serializable {

	private int orderId;
	private int statusId;
	private Date lastModifiedTm;

	public OrderStatusId() {
		// Do nothing... Hibernate needs this mandatory
	}

	public OrderStatusId(int orderId, int statusId, Date lastModifiedTm) {
		this.orderId = orderId;
		this.statusId = statusId;
		this.lastModifiedTm = lastModifiedTm;
	}

	@Column(name = "ORDER_ID", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "STATUS_ID", nullable = false)
	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	@Column(name = "LAST_MODIFIED_TM", nullable = false, length = 19)
	public Date getLastModifiedTm() {
		return this.lastModifiedTm;
	}

	public void setLastModifiedTm(Date lastModifiedTm) {
		this.lastModifiedTm = lastModifiedTm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderStatusId))
			return false;
		OrderStatusId castOther = (OrderStatusId) other;

		return (this.getOrderId() == castOther.getOrderId())
				&& (this.getStatusId() == castOther.getStatusId())
				&& ((this.getLastModifiedTm() == castOther.getLastModifiedTm()) || (this
						.getLastModifiedTm() != null
						&& castOther.getLastModifiedTm() != null && this
						.getLastModifiedTm().equals(
								castOther.getLastModifiedTm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderId();
		result = 37 * result + this.getStatusId();
		result = 37
				* result
				+ (getLastModifiedTm() == null ? 0 : this.getLastModifiedTm()
						.hashCode());
		return result;
	}

}
