package com.hpe.calEStore.dao.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductOrderId generated by hbm2java
 */
@Embeddable
public class ProductOrderId implements java.io.Serializable {

	private int orderId;
	private int productId;

	public ProductOrderId() {
		// Do nothing... Hibernate needs this mandatory
	}

	public ProductOrderId(int orderId, int productId) {
		this.orderId = orderId;
		this.productId = productId;
	}

	@Column(name = "ORDER_ID", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "PRODUCT_ID", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductOrderId))
			return false;
		ProductOrderId castOther = (ProductOrderId) other;

		return (this.getOrderId() == castOther.getOrderId())
				&& (this.getProductId() == castOther.getProductId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderId();
		result = 37 * result + this.getProductId();
		return result;
	}

}
