package com.hpe.calEStore.dao.entity;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductAspect generated by hbm2java
 */
@Entity
@Table(name = "product_aspect", catalog = "eshop")
public class ProductAspect implements java.io.Serializable {

	private ProductAspectId id;
	private Aspect aspect;
	private Product product;
	private String aspectVal;

	public ProductAspect() {
		// Do nothing... Hibernate needs this mandatory
	}

	public ProductAspect(ProductAspectId id, Aspect aspect, Product product,
			String aspectVal) {
		this.id = id;
		this.aspect = aspect;
		this.product = product;
		this.aspectVal = aspectVal;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "PRODUCT_ID", nullable = false)),
			@AttributeOverride(name = "aspectId", column = @Column(name = "ASPECT_ID", nullable = false)) })
	public ProductAspectId getId() {
		return this.id;
	}

	public void setId(ProductAspectId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ASPECT_ID", nullable = false, insertable = false, updatable = false)
	public Aspect getAspect() {
		return this.aspect;
	}

	public void setAspect(Aspect aspect) {
		this.aspect = aspect;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ID", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "ASPECT_VAL", nullable = false, length = 100)
	public String getAspectVal() {
		return this.aspectVal;
	}

	public void setAspectVal(String aspectVal) {
		this.aspectVal = aspectVal;
	}

}
