package com.hpe.calEStore.dao.entity;

// default package
// Generated Feb 15, 2017 5:41:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductOrderId generated by hbm2java
 */
@Embeddable
public class ProductOrderId implements java.io.Serializable {

	private int orderId;
	private int productId;
	private int qty;

	public ProductOrderId(int orderId, int productId, int qty) {
		this.orderId = orderId;
		this.productId = productId;
		this.qty = qty;
	}

	@Column(name = "ORDER_ID", nullable = false)
	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	@Column(name = "PRODUCT_ID", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "QTY", nullable = false)
	public int getQty() {
		return this.qty;
	}

	public void setQty(int qty) {
		this.qty = qty;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductOrderId))
			return false;
		ProductOrderId castOther = (ProductOrderId) other;

		return (this.getOrderId() == castOther.getOrderId())
				&& (this.getProductId() == castOther.getProductId())
				&& (this.getQty() == castOther.getQty());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderId();
		result = 37 * result + this.getProductId();
		result = 37 * result + this.getQty();
		return result;
	}

}
