package com.hpe.calEStore.dao.entity;

// default package
// Generated Feb 15, 2017 5:41:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ProductAspect generated by hbm2java
 */
@Entity
@Table(name = "product_aspect", catalog = "eshop")
public class ProductAspect implements java.io.Serializable {

	private int productId;
	private Aspect aspect;
	private Product product;
	private String aspectVal;


	public ProductAspect(Aspect aspect, Product product, String aspectVal) {
		this.aspect = aspect;
		this.product = product;
		this.aspectVal = aspectVal;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "product"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "PRODUCT_ID", unique = true, nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ASPECT_ID", nullable = false)
	public Aspect getAspect() {
		return this.aspect;
	}

	public void setAspect(Aspect aspect) {
		this.aspect = aspect;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "ASPECT_VAL", nullable = false, length = 100)
	public String getAspectVal() {
		return this.aspectVal;
	}

	public void setAspectVal(String aspectVal) {
		this.aspectVal = aspectVal;
	}

}
