package com.hpe.calEStore.dao.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductAspectId generated by hbm2java
 */
@Embeddable
public class ProductAspectId implements java.io.Serializable {

	private int productId;
	private int aspectId;

	public ProductAspectId() {
		// Do nothing... Hibernate needs this mandatory
	}

	public ProductAspectId(int productId, int aspectId) {
		this.productId = productId;
		this.aspectId = aspectId;
	}

	@Column(name = "PRODUCT_ID", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "ASPECT_ID", nullable = false)
	public int getAspectId() {
		return this.aspectId;
	}

	public void setAspectId(int aspectId) {
		this.aspectId = aspectId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductAspectId))
			return false;
		ProductAspectId castOther = (ProductAspectId) other;

		return (this.getProductId() == castOther.getProductId())
				&& (this.getAspectId() == castOther.getAspectId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + this.getAspectId();
		return result;
	}

}
