package com.hpe.calEStore.dao.entity;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TReportType2 generated by hbm2java
 */
@Entity
@Table(name = "T_REPORT_TYPE2")
public class TReportType2 implements java.io.Serializable {

	private Integer kpiId;
	private int kpiNumber;
	private String kpiDesc;
	private String userType;
	private String statusType;
	private String departmentName;
	private String weekId;
	private String vendorName;
	private Integer categoryName;
	private Integer valueForKpi;
	private Date createdDate;

	public TReportType2() {
	}

	public TReportType2(int kpiNumber, String userType, String statusType,
			Date createdDate) {
		this.kpiNumber = kpiNumber;
		this.userType = userType;
		this.statusType = statusType;
		this.createdDate = createdDate;
	}

	public TReportType2(int kpiNumber, String kpiDesc, String userType,
			String statusType, String departmentName, String weekId,
			String vendorName, Integer categoryName, Integer valueForKpi,
			Date createdDate) {
		this.kpiNumber = kpiNumber;
		this.kpiDesc = kpiDesc;
		this.userType = userType;
		this.statusType = statusType;
		this.departmentName = departmentName;
		this.weekId = weekId;
		this.vendorName = vendorName;
		this.categoryName = categoryName;
		this.valueForKpi = valueForKpi;
		this.createdDate = createdDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "KPI_ID", unique = true, nullable = false)
	public Integer getKpiId() {
		return this.kpiId;
	}

	public void setKpiId(Integer kpiId) {
		this.kpiId = kpiId;
	}

	@Column(name = "KPI_NUMBER", nullable = false)
	public int getKpiNumber() {
		return this.kpiNumber;
	}

	public void setKpiNumber(int kpiNumber) {
		this.kpiNumber = kpiNumber;
	}

	@Column(name = "KPI_Desc", length = 100)
	public String getKpiDesc() {
		return this.kpiDesc;
	}

	public void setKpiDesc(String kpiDesc) {
		this.kpiDesc = kpiDesc;
	}

	@Column(name = "User_Type", nullable = false, length = 45)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "Status_Type", nullable = false, length = 15)
	public String getStatusType() {
		return this.statusType;
	}

	public void setStatusType(String statusType) {
		this.statusType = statusType;
	}

	@Column(name = "Department_Name", length = 100)
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	@Column(name = "Week_ID", length = 15)
	public String getWeekId() {
		return this.weekId;
	}

	public void setWeekId(String weekId) {
		this.weekId = weekId;
	}

	@Column(name = "VendorName", length = 30)
	public String getVendorName() {
		return this.vendorName;
	}

	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}

	@Column(name = "Category_Name")
	public Integer getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(Integer categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "Value_for_KPI")
	public Integer getValueForKpi() {
		return this.valueForKpi;
	}

	public void setValueForKpi(Integer valueForKpi) {
		this.valueForKpi = valueForKpi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
