package com.hpe.calEStore.dao.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TReportType1 generated by hbm2java
 */
@Entity
@Table(name = "T_REPORT_TYPE1")
public class TReportType1 implements java.io.Serializable {

	private Integer kpiId;
	private int kpiNumber;
	private String kpiDesc;
	private String userType;
	private String valueForKpi;
	private Date createdDate;

	public TReportType1() {
	}

	public TReportType1(int kpiNumber, String userType, Date createdDate) {
		this.kpiNumber = kpiNumber;
		this.userType = userType;
		this.createdDate = createdDate;
	}

	public TReportType1(int kpiNumber, String kpiDesc, String userType,
			String valueForKpi, Date createdDate) {
		this.kpiNumber = kpiNumber;
		this.kpiDesc = kpiDesc;
		this.userType = userType;
		this.valueForKpi = valueForKpi;
		this.createdDate = createdDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "KPI_ID", unique = true, nullable = false)
	public Integer getKpiId() {
		return this.kpiId;
	}

	public void setKpiId(Integer kpiId) {
		this.kpiId = kpiId;
	}

	@Column(name = "KPI_Number", nullable = false)
	public int getKpiNumber() {
		return this.kpiNumber;
	}

	public void setKpiNumber(int kpiNumber) {
		this.kpiNumber = kpiNumber;
	}

	@Column(name = "KPI_DESC", length = 100)
	public String getKpiDesc() {
		return this.kpiDesc;
	}

	public void setKpiDesc(String kpiDesc) {
		this.kpiDesc = kpiDesc;
	}

	@Column(name = "USER_TYPE", nullable = false, length = 10)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "Value_For_KPI", length = 100)
	public String getValueForKpi() {
		return this.valueForKpi;
	}

	public void setValueForKpi(String valueForKpi) {
		this.valueForKpi = valueForKpi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
